### PR TITLE
youtube video player static page

### PR DESCRIPTION
**Pull request by tirthajyoti-ghosh**
This static page contains:
- Navigation Bar
- Video Player section. Video player implemented with iframe.
- Information about the video(title, no. of views, like/dislike/share/save buttons, uploader name, and avatar, subscribe button)
- Sidebar containing Up Next and Recommended videos.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job! 

#### Descriptive Readme
Your Readme file will benefit from a work up. When you start to apply to jobs, potential employers will go through your Github account to see the way you work and may form an opinion of the kind of developer you are from what they see. As such, it is important to ensure that all your repositories look very neat and professional. That being said, please consider this [example](https://github.com/Oluwadamilareolusakin/show-junkie-frontend/blob/master/README.md) as what your Readme File should look like! :smile: 

#### Restructuring Project directories [Optional]
Please consider restructuring your project directory by grouping common files like your images for instance, into a specific folder. This can improve your workflow by ensuring you don't spend too much time searching through files to find a specific one, especially in really large projects. It also makes your project directory tidier, peer friendly and professional. Consider this change :+1: 


#### Recommended videos
You have both done a great job getting the required elements unto the page, all you have to do now is correctly position them. Your recommended videos section will look great when you are finished, however, it currently doesn't look its best. Please take a second look at it's alignment and make the approriate corrections in comparison with the original site.

#### Live link
Please remember to update the live link in your project to point to the actual website. My go to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+1: 
### Summary
Splendid job so far team! Please look into my few comments above this paragraph, make appropriate corrections and request another review. All the best in this and subsequent projects and see you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this within the hour for some feedback :smile:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job team! @tirthajyoti-ghosh and @vzdrizhni 
Please look at this small issue I found, correct and submit for another review:

#### Recommended Videos Section
Your recommended videos section is encroaching into the main video section
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @tirthajyoti-ghosh @vzdrizhni,
Your recommended videos section and the current video aren't aligned, your current video is below the recommended videos section, please fix this and request for another code review.
Screenshot

[OPTIONAL]
- I noticed you added stickler, which is not a requirement for this project, but good job adding it, please fix the errors.

## Status: Changes Required
_Feel free to reach out to me on slack (fatima), if you have any questions, I'd be happy to help._

**Review by fatymahmed — APPROVED** [review]
## Hi @tirthajyoti-ghosh @vzdrizhni,
Great job making all changes 😀😀😀,
### **Congratulations** on completing the project 👏👏
You can go ahead and merge the pull request and don't forget to submit your project completion form.
Good luck in your next projects 😀

## Status: Approved

**Pull request merged**
